#!/bin/bash

#should I do this on startvnc?
vglclient &

#freeview is multi-window app, so we need windowmaanger
XFCE_PANEL_MIGRATE_DEFAULT=true startxfce4 &

source $FREESURFER_HOME/SetUpFreeSurfer.sh

#for neuro/freesurfer
if [ -d /input/output/mri ];
then
    vglrun /usr/local/freesurfer/bin/freeview -layout 4 -viewport 3d \
	    -v /input/output/mri/T1.mgz \
	    /input/output/mri/wm.mgz \
	    /input/output/mri/brainmask.mgz \
	    /input/output/mri/aseg.mgz:colormap=lut:opacity=0.2 \
	    -f /input/output/surf/lh.white:edgecolor=blue \
	    /input/output/surf/lh.pial:edgecolor=red \
	    /input/output/surf/rh.white:edgecolor=blue \
	    /input/output/surf/rh.pial:edgecolor=red
    exit
fi

#for neuro/track/trk
if [ -f /input/track.trk ];
then
    vglrun /usr/local/freesurfer/bin/freeview -tract /input/track.trk -layout 1
    exit
fi

#all else just show any .nii.gz
vglrun /usr/local/freesurfer/bin/freeview `find /input -name *.nii.gz`

#sleep 3600
